language: rust

# Cache `cargo install`ed tools, but don't cache the project's `target`
# directory (which ends up over-caching and filling all disk space!)
# https://levans.fr/rust_travis_cache.html
cache:
  directories:
    - /home/travis/.cargo

before_cache:
  # But don't cache the cargo registry
  - rm -rf /home/travis/.cargo/registry
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

jobs:
  include:
  - os: linux
    rust: stable
    env: BUILD_MODE=build
  - os: linux
    rust: stable
    env: BUILD_MODE=integration
  - os: osx
    rust: stable
    env: BUILD_MODE=build
  - os: osx
    rust: stable
    env: BUILD_MODE=integration

before_install:
- >
  if [[ "$TRAVIS_OS_NAME" == "linux" ]];then
    sudo ci/dependencies.sh;
  fi

script:
- ci/run.sh
