language: rust

jobs:
  include:
  - os: linux
    rust: stable
    env: BUILD_MODE=build
  - os: linux
    rust: stable
    env: BUILD_MODE=integration
  - os: osx
    rust: stable
    env: BUILD_MODE=build
  - os: osx
    rust: stable
    env: BUILD_MODE=integration

before_install:
- >
  if [[ "$TRAVIS_OS_NAME" == "linux" ]];then
    sudo ci/dependencies.sh;
  fi

script:
- ci/run.sh
